### PR TITLE
Update CN wording in game in questing profiles.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by sodimm** [comment]
I'm not around or able to test these, so i'm assuming they were before submitting the pull request.

**Comment by sodimm** [comment]
Pull request broke profiles, so i've reverted the merge.

**Comment by ghost** [comment]
Just checking what was the issue with CN in the profile? It's working properly on my end.

**Comment by sodimm** [comment]
I don't know, the merge was reversed before i returned to RB. I will be checking them as soon as current jobs are addressed. But I'm guessing a rogue ";" missing somewhere that was bringing up an error on profile compile. I'll re-add them when I have time to fully test their loads.

**Pull request merged**
